/*
Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
#include <iostream>

int main()
{
    int t;
    std::cin >> t;
    for(int a0 = 0; a0 < t; a0++){
        long n;
        std::cin >> n;

        unsigned long long term_1 = 1;
        unsigned long long term_2 = 2;
        unsigned long long temp = 0;
        unsigned long long sum = term_2;

        while (term_2 < n){
            temp = term_2;
            term_2 += term_1;
            term_1 = temp;

            if (term_2 % 2 == 0 & term_2 < n){
                sum += term_2;
            } 
        }
        std::cout << sum << std::endl;
    }
    
    return 0;
}