"""
Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def main(N):
    term_1 = 1
    term_2 = 2
    temp = 0
    sum = term_2

    while term_2 < N:
        temp = term_2
        term_2 += term_1
        term_1 = temp

        if term_2 % 2 == 0 and term_2 < N:
            sum += term_2
    
    
    return sum

if __name__ == "__main__":
    print(main(4000000))